### ISSUE TITLE
DOCX files return mime: 'application/zip'

### ISSUE THREAD

**Issue by kev1awlor** [redmundas/file-type-mime#267]
![image](https://github.com/user-attachments/assets/57ad33dc-7126-4b0c-af09-6382782eebb6)

Expected result: `application/vnd.openxmlformats-officedocument.wordprocessingml.document`

**Comment by redmundas** [comment]
thanks for the issue. will work on the fix asap

**Comment by redmundas** [comment]
released file-type-mime@0.4.2

**Comment by redmundas** [comment]
@kev1awlor let me know if it fixed the problem for you

**Comment by kev1awlor** [comment]
> @kev1awlor let me know if it fixed the problem for you

Working 100% ... thanks for the speedy turnaround & thanks for the great package!
