### ISSUE TITLE
DOCX files created with WPS return mime: 'application/zip'

### ISSUE THREAD

**Issue by deLTreeTech** [redmundas/file-type-mime#284]
I saw that you have already resolved something similar to this but DOCX file I created using WPS on Mac returns 'application/zip' as mime.

When I created DOCX with Microsoft Office on Windows, it works correctly.

Can you look into this?

**Comment by redmundas** [comment]
@deLTreeTech can I ask what is WPS?
could you also drop a sample doc?
I would gladly look into it

**Comment by deLTreeTech** [comment]
Thanks for your prompt response.

WPS is an open source Office Suite (https://www.wps.com)

Attached is a sample document

[Test Document.docx](https://github.com/user-attachments/files/16378436/Test.Document.docx)

**Comment by redmundas** [comment]
@deLTreeTech should be fixed in v0.4.3
let me know if it works for you

**Comment by deLTreeTech** [comment]
Working perfectly. Thanks for your prompt action
