### ISSUE TITLE
No result for text, json, javascript etc files on node

### ISSUE THREAD

**Issue by tdomzalski** [redmundas/file-type-mime#330]
Using the following code:

```
import { parse } from "file-type-mime";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const file = resolve("./path/to/file.json");
const buffer = readFileSync(file);
const result = parse(buffer);

console.log("MIME_TYPE", result);
```

I get the `result` to be `undefined`.
I tried with txt files, json files, javascript files - the same result -> `undefined`.

Reproduced on node 20 and 22 with "file-type-mime": "^0.4.3"

**Comment by redmundas** [comment]
types for text based files are only available via `extra` flag in the options object:
```
const result = parse(buffer, { extra: true });
```
